-- Create server prefix db
CREATE TABLE SERVER_PREFIX (
	SERVER_ID bigint NOT NULL PRIMARY KEY,
	PREFIX VARCHAR(3) NOT NULL
);

-- Create timer db
CREATE TABLE USER_TIMERS (
	ID SERIAL PRIMARY KEY NOT NULL,
	USER_ID bigint NOT NULL,
	END_DATE BIGINT NOT NULL,
	SERVER_ID bigint NOT NULL
);

-- Create todos
CREATE TABLE USER_TODO (
	ID SERIAL PRIMARY KEY NOT NULL,
	USER_ID bigint NOT NULL,
	SERVER_ID bigint NOT NULL,
	MESSAGE VARCHAR(250) NOT NULL,
	TIME_ADDED BIGINT NOT NULL
);

-- Create link between emoji and role
CREATE TABLE REACT_EMOJI_ROLE_MATCH (
    ID SERIAL PRIMARY KEY NOT NULL,
    REACT_EMOJI VARCHAR NOT NULL,
    ROLE_ID bigint NOT NULL
);

-- Create reactionary table
CREATE TABLE REACTIONARIES (
    ID SERIAL PRIMARY KEY NOT NULL,
    MESSAGE_ID bigint NOT NULL,
    USER_ID bigint NOT NULL,
    SERVER_ID bigint NOT NULL,
    REACT_EMOJI_LINKS VARCHAR NOT NULL
);

-- Create saved messages db
CREATE TABLE REACT_SAVED_MESSAGES (
    ID SERIAL PRIMARY KEY NOT NULL,
    USER_ID bigint NOT NULL,
    MESSAGE_CONTENT VARCHAR NOT NULL,
    REACTIONARY_ID int NOT NULL
);